name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
   runs-on: ubuntu-18.04
   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install 
      run: npm install 
    - name: build
      run: npm run build
    - name: lint
      run: npm run lint
    - name: deploy to heroku
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
      uses: akhileshns/heroku-deploy@v3.12.12
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: phonebookupgraded
        heroku_email: hakonenweeti@gmail.com
        healthcheck: https://phonebookupgraded.herokuapp.com/health
        checkstring: ok
        rollbackonhealthcheckfailed: true
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMB: patch
    - name: Send success to slack
      if: ${{ success() }} 
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: message,commit,took 
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
    - name: Send failure to slack
      if: ${{ failure() }} 
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: message,commit,took 
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}